### ISSUE TITLE
run test_widerface.py failed

### ISSUE THREAD

**Issue by Jar7** [derronqi/yolov7-face#31]
```
Traceback (most recent call last):
  File "test_widerface.py", line 134, in <module>
    detect(opt=opt)
  File "test_widerface.py", line 43, in detect
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/liaojiaqi/yolov7-face/models/yolo.py", line 362, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/liaojiaqi/yolov7-face/models/yolo.py", line 396, in forward_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/liaojiaqi/yolov7-face/models/yolo.py", line 65, in forward
    if self.nkpt is None or self.nkpt==0:
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'Detect' object has no attribute 'nkpt'
```
Hello!
I simply run python test_widerface.py, and failed. Could you please tell how to fix this. Which script could I infer some images? 
Thank you.

**Comment by anandravi24** [comment]
Try providing the correct weights argument (yolov7face) while running the test_widerface.py.
